matches:
  # Lettres grecques
  - trigger: "/alp"
    replace: "Œ±"
  - trigger: "/bet"
    replace: "Œ≤"
  - trigger: "/gam"
    replace: "Œ≥"
  - trigger: "/del"
    replace: "Œ¥"
  - trigger: "/eps"
    replace: "Œµ"
  - trigger: "/zet"
    replace: "Œ∂"
  - trigger: "/eta"
    replace: "Œ∑"
  - trigger: "/the"
    replace: "Œ∏"
  - trigger: "/iot"
    replace: "Œπ"
  - trigger: "/kap"
    replace: "Œ∫"
  - trigger: "/lam"
    replace: "Œª"
  - trigger: "/mu"
    replace: "Œº"
  - trigger: "/nu"
    replace: "ŒΩ"
  - trigger: "/xi"
    replace: "Œæ"
  - trigger: "/omi"
    replace: "Œø"
  - trigger: "/pi"
    replace: "œÄ"
  - trigger: "/rho"
    replace: "œÅ"
  - trigger: "/sig"
    replace: "œÉ"
  - trigger: "/tau"
    replace: "œÑ"
  - trigger: "/ups"
    replace: "œÖ"
  - trigger: "/phi"
    replace: "œÜ"
  - trigger: "/chi"
    replace: "œá"
  - trigger: "/psi"
    replace: "œà"
  - trigger: "/ome"
    replace: "œâ"
  - trigger: "/k2"
    replace: "œá¬≤"

  - trigger: "/grad"
    replace: "‚àá"


  # Lettres grecques majuscules
  - trigger: "/ALP"
    replace: "Œë"
  - trigger: "/BET"
    replace: "Œí"
  - trigger: "/GAM"
    replace: "Œì"
  - trigger: "/DEL"
    replace: "Œî"
  - trigger: "/EPS"
    replace: "Œï"
  - trigger: "/ZET"
    replace: "Œñ"
  - trigger: "/ETA"
    replace: "Œó"
  - trigger: "/THE"
    replace: "Œò"
  - trigger: "/IOT"
    replace: "Œô"
  - trigger: "/KAP"
    replace: "Œö"
  - trigger: "/LAM"
    replace: "Œõ"
  - trigger: "/MU"
    replace: "Œú"
  - trigger: "/NU"
    replace: "Œù"
  - trigger: "/XI"
    replace: "Œû"
  - trigger: "/OMI"
    replace: "Œü"
  - trigger: "/PI"
    replace: "Œ†"
  - trigger: "/RHO"
    replace: "Œ°"
  - trigger: "/SIG"
    replace: "Œ£"
  - trigger: "/TAU"
    replace: "Œ§"
  - trigger: "/UPS"
    replace: "Œ•"
  - trigger: "/PHI"
    replace: "Œ¶"
  - trigger: "/CHI"
    replace: "Œß"
  - trigger: "/PSI"
    replace: "Œ®"
  - trigger: "/OME"
    replace: "Œ©"





  # Symboles math√©matiques
  - trigger: "/inf"
    replace: "‚àû"
  - trigger: "/neq"
    replace: "‚â†"
  - trigger: "/geq"
    replace: "‚â•"
  - trigger: "/leq"
    replace: "‚â§"
  - trigger: "/sqrt"
    replace: "‚àö"
  - trigger: "/sum"
    replace: "$\\sum{}$"
  - trigger: "/int"
    replace: "$\\int{}$ "
  - trigger: "/pm"
    replace: "¬±"
  - trigger: "/times"
    replace: "√ó"
  - trigger: "/div"
    replace: "√∑"
  - trigger: "/eq"
    replace: "‚Üî"
  - trigger: "~="
    replace: "‚âà"
  - trigger: "/imp"
    replace: "‚ü∂"
  - trigger: "->"
    replace: "‚ü∂"


  - trigger: "normexyn"
    replace: "‚Äñ(x‚Çô, y‚Çô)‚Äñ"

  - trigger: "normexy"
    replace: "‚Äñ(x, y)‚Äñ"

  - trigger: "/norme"
    replace: "‚Äñ‚Äñ"

  - trigger: "/xn"
    replace: "x‚Çô"

  - trigger: "/yn"
    replace: "y‚Çô"


  # Logique
  - trigger: "/or "
    replace: "‚à® "
  - trigger: "/and "
    replace: "‚àß "

  - trigger: "/ou "
    replace: "‚à® "
  - trigger: "/et "
    replace: "‚àß "

  - trigger: "tinf"
    replace: "‚ü∂ ‚àû"
  - trigger: "/and "
    replace: "‚àß "

  - trigger: "/inn "
    replace: "‚àà"
  - trigger: "/nin "
    replace: "‚àâ "

    
  - trigger: "/qql "
    replace: "‚àÄ "
  - trigger: "/ilya "
    replace: "‚àÉ "

  - trigger: "/scal"
    replace: "‚ü®‚ü©"


  - trigger: "+med"
    replace: "üîº"

  - trigger: "+high"
    replace: "‚è´"

  - trigger: "+hh"
    replace: "üî∫"

  - trigger: "+lwo"
    replace: "üîΩ"

  - trigger: "+ll"
    replace: "‚è¨"

  - trigger: "/a/"
    replace: "‚ö†Ô∏è "




  - trigger: "+tdy"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date '+%Y-%m-%d'"

  - trigger: "+mon"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Mon '+%Y-%m-%d'"

  - trigger: "+tue"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Tue '+%Y-%m-%d'"

  - trigger: "+wed"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Wed '+%Y-%m-%d'"

  - trigger: "+thu"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Thu '+%Y-%m-%d'"

  - trigger: "+fri"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Fri '+%Y-%m-%d'"

  - trigger: "+sat"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Sat '+%Y-%m-%d'"

  - trigger: "+sun"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+Sun '+%Y-%m-%d'"

  - trigger: "+tmr"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v+1d '+%Y-%m-%d'"

  - trigger: "+yst"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date -v-1d '+%Y-%m-%d'"


  # Exposants 0-9 + n
  - trigger: "/0"
    replace: "‚Å∞"
  - trigger: "/1"
    replace: "¬π"
  - trigger: "/2"
    replace: "¬≤"
  - trigger: "/3"
    replace: "¬≥"
  - trigger: "/4"
    replace: "‚Å¥"
  - trigger: "/5"
    replace: "‚Åµ"
  - trigger: "/6"
    replace: "‚Å∂"
  - trigger: "/7"
    replace: "‚Å∑"
  - trigger: "/8"
    replace: "‚Å∏"
  - trigger: "/9"
    replace: "‚Åπ"
  - trigger: "/n"
    replace: "‚Åø"
  - trigger: "/)"
    replace: "‚Åª¬π"
  - trigger: "/T"
    replace: "·µÄ"

  # Indices 0-9 + n
  - trigger: "_0"
    replace: "‚ÇÄ"
  - trigger: "_1"
    replace: "‚ÇÅ"
  - trigger: "_2"
    replace: "‚ÇÇ"
  - trigger: "_3"
    replace: "‚ÇÉ"
  - trigger: "_4"
    replace: "‚ÇÑ"
  - trigger: "_5"
    replace: "‚ÇÖ"
  - trigger: "_6"
    replace: "‚ÇÜ"
  - trigger: "_7"
    replace: "‚Çá"
  - trigger: "_8"
    replace: "‚Çà"
  - trigger: "_9"
    replace: "‚Çâ"
  - trigger: "_n"
    replace: "‚Çô"
  - trigger: "_i"
    replace: "·µ¢"
